name: research-audio
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - onnxruntime
  - pip
  - pip:
    - piper-tts
    - pathvalidate
    - pydub
    - psutil
    - requests
    - anthropic
